### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by thiagodelmotte** [FokkeZB/TiCons-CLI#40]
http://ticons.fokkezb.nl/

504 Gateway Time-out
The server didn't respond in time.

Server is down after submit.

**Comment by FokkeZB** [comment]
Happens every now and then with peak usage. Restores itself, which it now has.

**Comment by thiagodelmotte** [comment]
Hum...but I am trying to use since 2 days ago, and no response from server. Now I'm getting 500.

504 Gateway Time-out
The server didn't respond in time.

**Comment by FokkeZB** [comment]
It's now 500 because I'm restarting :)

**Comment by FokkeZB** [comment]
You are aware that the server just wraps the CLI? The server has difficulties resizing and compressing too many files at the same time, but you can just copy and paste the displayed CLI commands and use those instead on your own system, which is what I'd always suggest. Why go to a site when you can do it from the CLI?

**Comment by thiagodelmotte** [comment]
Well, I am not using any system. I am using your webpage, just to make ONE zip for a app.

**Comment by FokkeZB** [comment]
I'm sure you're on a Mac or Windows computer when you develop the app ;)

Anyway, this **is** something I try to improve, but for now you'll have to live with some outages every now and then when there's a lot of traffic.

And at the moment it's not working because somehow zip is missing on the server. On that.

**Comment by thiagodelmotte** [comment]
OK! No problem! Thank you!
